name = "news-cron-job"
main = "src/index.ts"
compatibility_date = "2024-05-29"


[triggers]
crons = ["* */12 * * *"]

[[kv_namespaces]]
binding = "KV"
id = "b6783170bcde4c6f9d9e6152dc8d1027"

[ai]
binding = "AI"